version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: ctf_postgres
    environment:
      POSTGRES_USER: ctfuser
      POSTGRES_PASSWORD: ctfpass
      POSTGRES_DB: ctfdb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    build: .
    container_name: custom_sandbox
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=ctfuser
      - DB_PASS=ctfpass
      - DB_NAME=ctfdb
    volumes:
      - .:/app
    command: ["nodemon", "--inspect=0.0.0.0:9229", "server.js"]
