version: "3.8"

services:

  frontend:
    build: ./src/frontend
    restart: always
    expose:
      - "3000"
    working_dir: /app
    networks:
      - internal
    depends_on:
      backend:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"

  backend:
    build: ./src/backend
    restart: always
    expose:
      - "8000"
    volumes:
      - ./src/backend:/app
    networks:
      - internal
    environment:
      - SECRET_KEY=de64e0771f22bc05ecf526862374c5fd
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - ADMIN_EMAIL=admin@ferrari.com
      - ADMIN_PASSWORD=1a07e0185d47012a66fec6c4dbf2a96d
      - MONGODB_URI=mongodb://mongo:27017
    depends_on:
      mongo:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
          
  mongo:
    image: mongo:latest
    command: ['mongod', '--quiet']
    restart: always
    expose:
      - "27017"
    networks:
      - internal
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
  
  bot:
    build:
      context: ./src/bot
      args:
        - BROWSER=chromium
    restart: always
    expose:
      - "3000"
    environment:
      APPNAME: Admin
      APPURL: http://proxy:80
      APPURLREGEX: ^https?://proxy:80(/.*)?$
      APPFLAG: COMPFEST17{fake_flag}
      APPLIMIT: 2
      APPLIMITTIME: 60
      USE_PROXY: 1
      DISPLAY: ${DISPLAY}
      APPEMAIL: admin@ferrari.com
      APPPASS: 1a07e0185d47012a66fec6c4dbf2a96d
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"

  proxy:
    image: nginx:latest
    restart: always
    ports:
      - 7303:80
    volumes:
      - ./src/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - bot
      - backend
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"

networks:
  internal:
